### ISSUE TITLE
Add screenshots for the default slack themes in README

### ISSUE THREAD

**Issue by sachinh19** [sachinh19/slack-themes#1]
The requirement here is to add screenshots under each hex code for the default themes present in the README.

Points to keep in mind:

1. Make sure the screenshot size is small so that users will slow internet connection can open this README without much hassle.
2. Most importantly the text in the screenshot should be decent and not be offensive in any way. Such screenshots will not pass PR approval.
3. Add the screenshots under `assets/images/` folder where the name of the screenshot should be the name of the theme.
e.g. The screenshot for aubergine should be aubergine.jpg or aubergine.png or any other extension that works best.
3. Add an collapsible section with message `Click to see screenshot` under each hex code and add the screenshot inside the collapsible section. This should be done so that all collapsible sections are closed whenever a user opens the README and is able to scroll through easily without having to see all screenshots.

**Comment by Ckrielle** [comment]
Hello there, I would be interested to work on this

**Comment by sachinh19** [comment]
@Ckrielle assigned it to you. Let me know if you have any questions.

**Comment by Ckrielle** [comment]
@sachinh19 Gonna work on this now

**Comment by sachinh19** [comment]
Thanks for working on these two issues. Appreciate your contribution.

**Comment by sachinh19** [comment]
Reopening to address the collapsible markdown changes.
