### ISSUE TITLE
Add README instructions on how to set Slack theme on Windows

### ISSUE THREAD

**Issue by sachinh19** [sachinh19/slack-themes#2]
There is an existing section in README on how to set slack themes on Mac. Need a similar section for Windows.

**Comment by Ckrielle** [comment]
Hello there, I would be interested to work on this.

**Comment by sachinh19** [comment]
@Ckrielle assigned it to you.

**Comment by sachinh19** [comment]
@Ckrielle any timeline on when you would be completing this task?

**Comment by Ckrielle** [comment]
@sachinh19 Within the day
