### ISSUE TITLE
Add commit message guidelines

### ISSUE THREAD

**Issue by sachinh19** [sachinh19/slack-themes#3]
The requirement here is to have some commit message guidelines which aren't too difficult to follow, at the same time have some standard in place so all our commit messages are of the same format.

The assignee should add this section in CONTRIBUTING.md

**Comment by 96RadhikaJadhav** [comment]
@sachinh19  Can I work on it?

**Comment by sachinh19** [comment]
@96RadhikaJadhav - assigning it to you.

**Comment by sachinh19** [comment]
@96RadhikaJadhav thanks for working on this, please do contribute if you can to other issues in this repository.
